FROM golang:1.8.3

# glide
RUN wget https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-linux-amd64.tar.gz && \
    tar xvzf glide-v0.12.3-linux-amd64.tar.gz --strip-components 1 -C /usr/local/bin linux-amd64/glide && \
    rm -f glide-v0.12.3-linux-amd64.tar.gz
